services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    networks:
      - table_booking_network
    volumes: 
      - ./TableBooking.Model/Seed/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  api:
   build:
       context: .
       dockerfile: ./TableBooking.Api/Dockerfile
   ports:
     - "7012:7012"
   depends_on:
     - db
   networks:
       - table_booking_network
  
networks:
  table_booking_network:
    name: table_booking_network
    driver: bridge